name: GS64 Docker Tests
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
   unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gs_version:
          - "3.7.0"
          - "3.7.1"
    name: GS64 v{{ matrix.gs_version }} Docker Tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Configure keyfile
        run: |
          echo "$GS_KEYFILE" > ./.docker/gs64/gemstone.key
        env:
          GS_KEYFILE: ${{ secrets.GS_KEYFILE }}
      - name: Run tests using Docker
        run: ./.docker/gs64/docker-tests.sh {{ matrix.gs_version }}
      - name: Remove keyfile
        run: rm -f ./.docker/gs64/gemstone.key
