name: Build and Publish GS64 Docker Images
on:
  workflow_dispatch:
  push:
    branches: 
     - '**'
    tags:
      - 'v*.*.*'
  pull_request:
jobs:
   build_and_publish:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "3.7.0"
          - "3.7.1"
    name: Build and Publish Docker images
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/launchpad-gs64-${{ matrix.version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/gs64-${{ matrix.version }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          secrets: GIT_AUTH_TOKEN=${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        if: ${{ github.event_name != 'pull_request' && matrix.version == '3.7.1' }}
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/launchpad-gs64-${{ matrix.version }}:${{ github.ref_name }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          limit-severities-for-sarif: true
          ignore-unfixed: true
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ github.event_name != 'pull_request' && matrix.version == '3.7.1' }}
        with:
          sarif_file: 'trivy-results.sarif'
          category: ghcr.io/${{ github.repository_owner }}/launchpad-gs64-${{ matrix.version }}:${{ github.ref_name }}

